name: phycloneCustom
channels:
  - numba
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - click=8.3.1=pyh8f84b5b_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - cpython=3.14.2=py314hd8ed1ab_100
  - joblib=1.5.2=pyhd8ed1ab_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libblas=3.11.0=4_h4a7cf45_openblas
  - libcblas=3.11.0=4_h0358290_openblas
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - liblapack=3.11.0=4_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libsqlite=3.51.1=h0c1763c_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libuuid=2.41.2=h5347b49_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.46.0=py314hbe36340_0
  - ncurses=6.5=h2d0b736_3
  - networkx=3.6.1=pyhcf101f3_0
  - numba=0.63.1=np2.3py3.14h3d39851_g7484a86bd_0
  - numpy=2.3.5=py314h2b28147_0
  - openssl=3.6.0=h26f9b46_0
  - pandas=2.3.3=py314ha0b5721_2
  - pip=25.3=pyh145f28c_0
  - python=3.14.2=h32b2ec7_100_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.14.2=h4df99d1_100
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py314he82b845_1
  - python_abi=3.14=8_cp314
  - pytz=2025.2=pyhd8ed1ab_0
  - readline=8.2=h8c095d6_2
  - rustworkx=0.17.1=py310h1570de5_3
  - scikit-learn=1.8.0=py314hb68c362_0
  - scipy=1.16.3=py314he7377e1_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tqdm=4.67.1=pyhd8ed1ab_1
  - tzdata=2025b=h8577fbf_1
  - xxhash=0.8.3=hb47aa4a_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - phyclone==0.7.1
prefix: /home/giuliosp/anaconda3/envs/phycloneCustom
